### ISSUE TITLE
Http adapter: Play Framework Integration

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#111]
In order to gracefully integrate with `Play Framework` we should provide appropriate implicit instances of their Action composers to transparently use Freestyle programs as return values in Play Framework Controllers without the need to manually executing them to Future. https://www.playframework.com/documentation/2.5.x/ScalaActionsComposition

In an ideal scenario a user would simply `import freestyle.http.playframework.implicits._` and automatically embed a Freestyle along these lines:
```scala
    val bids: FreeS[F, Bids] = ???
    def route(args : String) = FreeSAction { 
        ...
    }
```

This feature will allow user to define purely functional programs whose resulting values are transparently returned in Http Responses. Once this feature is implemented appropriate documentation should go under `Integrations -> Http -> PlayFramework`.

**Comment by peterneyens** [comment]
Added in #125.
