### ISSUE TITLE
Http adapter : Finch Integration

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#112]
In order to gracefully integrate with `Finch` we should provide appropriate `Endpoint` instances that allow Freestyle programs to be used as returning values properly interpreting to `A => Future[Output[B]]` or `A => Output[B]` from which endpoints can be generated. https://finagle.github.io/finch/user-guide.html#outputs

In an ideal scenario a user would simply `import freestyle.http.finch.implicits._` and automatically embed a Freestyle program like so:
```scala
val bids: FreeS[F, Output[Bids]] = ???
val e = get(/) { bids }
```

This feature will allow user to define purely functional programs with Freestyle whose resulting values are transparently returned in Http Responses. Once this feature is implemented appropriate documentation should go under `Integrations -> Http -> Finch`

**Comment by peterneyens** [comment]
Added in #124.
