### ISSUE TITLE
Http adapter - Http4s Integration

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#113]
In order to gracefully integrate with `http4s` we should provide appropriate implicit instances that convert a `FreeS` program to a `fs2.Task` both implicit and explicit conversions

In an ideal scenario a user would simply `import freestyle.http.http4s.implicits._` and automatically embed a Freestyle program like so:

```scala
val bids: FreeS[F, Bids] = ???
val bidsService = HttpService {
  case GET -> Root / "bids" =>
    Ok(bids)
}
```
Since we already have a `fs2` module we can provide syntax there `frees.toFS2Task` and then an implicit conversion in the `http-http4s` module that is brought into scope with this module implicits for http4s users to not worry about calling syntax directly.

This feature will allow users to define purely functional programs whose resulting values are transparently returned in Http Responses. Once this feature is implemented appropriate documentation should go under `Integrations -> Http -> http4s`

**Comment by peterneyens** [comment]
I think it should work out of the box with http4s as there seems to be an [`EntityEncoder` for natural tranformations](https://github.com/http4s/http4s/blob/cats/core/src/main/scala/org/http4s/EntityEncoder.scala#L100-L101).

And if you just want to use `fs2.Task` as a target, you don't need `freestyle-async-fs2` or `freestyle-fs2`, you just need the `fs2-cats` dependency that provides the necessary instances for `Task`.

**Comment by raulraja** [comment]
@peterneyens wouldn't we still need those for the `Capture` instances and the implicit conversion to avoid a call to `exec[Task]` ?

**Comment by peterneyens** [comment]
Yes, I forgot for a moment `exec` is `foldMap(interpreter)`.
