### ISSUE TITLE
Docs editorial review

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#139]
We need to have someone like @MaureenElsberry with more editorial knowledge than us do a pass to all the docs to ensure what we are saying makes sense and reads nicely.

**Comment by MaureenElsberry** [comment]
All these @raulraja? https://github.com/47deg/freestyle/tree/master/docs/src/main/tut/docs --- just want to make sure I'm heading to the right place before giving editorial pass...

**Comment by raulraja** [comment]
Yes, thank you, there still issues for new sections being worked on in this last sprint on preparation for 0.1.0. They are the open and in progress issues in the Project view

**Comment by MaureenElsberry** [comment]
Just for an FYI: This is in process - editing in separate doc so can implement in actually files quickly in one swoop.

**Comment by raulraja** [comment]
Thanks Maureen, I know you are busy these days. Feel free to review later on when all docs are in and we will hold the release until those are ready and meanwhile prepare for 0.2.0
