### ISSUE TITLE
scala 2.12 support?

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#140]
Could you please support scala 2.12? Published binary is 2.11 only and local compile gives

```
[info] Compiling 1 Scala source to /home/fommil/Projects/freestyle/freestyle-async-monix/jvm/target/scala-2.12/classes...
[info] Resolving org.typelevel#cats-kernel_2.12;0.9.0 ...
[warn] one warning found
[info] Done updating.
java.lang.NullPointerException
	at scala.reflect.internal.ReificationSupport$ReificationSupportImpl$SyntacticClassDef$.unapply(ReificationSupport.scala:353)
	at org.scalamacros.paradise.reflect.TreeInfo$ParadiseTreeInfo.loop$1(TreeInfo.scala:31)
```

(which I assume you know about, since you've made 2.12 the default)

**Comment by fommil** [comment]
note that docs are claiming 2.12 support (but I can't see any artifacts on maven central) http://frees.io/docs/ do you have custom repo?

**Comment by raulraja** [comment]
We are publishing snapshots to sonatype and we're getting ready for an official 0.1.0 to central. There should be snapshots for 2.11 and 2.12. We should have a final 0.1.0 in a couple of weeks https://github.com/47deg/freestyle/projects/1

**Comment by fommil** [comment]
ah, sweet. I'll add the relevant resolver in that case.

**Comment by fommil** [comment]
oh, that doesn't seem to work. Are the sonatype snapshot jars on jboss healthy? e.g. https://ci.fommil.com/fommil/drone-dynamic-agents/12

**Comment by raulraja** [comment]
:confused: , we are not publishing to jboss just sonatype which has the latest stuff from earlier this morning https://oss.sonatype.org/content/repositories/snapshots/com/47deg/freestyle_2.12/0.1.0-SNAPSHOT/ .
The URL in your CI seems to be pulling from Jboss which only contains the POM files https://repository.jboss.org/com/47deg/freestyle_2.12/0.1.0-SNAPSHOT/ . Not sure what's going on, maybe something badly cached in local ivy?

**Comment by fommil** [comment]
I have a jboss repository to work around http://stackoverflow.com/questions/41966066 but it looks like some SNAPSHOT poms made it onto jboss (I hate the jboss repo so much...)
