### ISSUE TITLE
jvm dependency pulling in sjs

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#141]
adding this to my project

```
libraryDependencies += "com.47deg" %% "freestyle" % "0.1.0-SNAPSHOT"
```

(with a `sbt freestyle/publishLocal`)

is pulling in a bunch of sjs libraries.

**Comment by raulraja** [comment]
`freestyle` is a cross project, try `sbt freestyleJVM/publishLocal` if you just want the JVM ones.

**Comment by fommil** [comment]
this also seems to happen with the poms you are publishing, e.g. https://repository.jboss.org/com/47deg/freestyle_2.12/0.1.0-SNAPSHOT/freestyle_2.12-0.1.0-SNAPSHOT.pom
