### ISSUE TITLE
scalac Position info weird inside a free trait

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#142]
hopefully this can be easily reproduced with pcplod

```scala
package algebra

import freestyle._

object Drone {
  sealed trait Response
  case class WorkQueue(items: Int) extends Response
  case class WorkActive(items: Int) extends Response

  @free trait Services[F[_]] {
    def receiveWorkQueue(): FreeS[F, WorkQueue]
    def receiveActiveWork(): FreeS[F, WorkActive]
  }
}
```

doing an ensime "type at point" anywhere inside the `Services` trait returns `Drone` instead of the actual type at point. e.g. I'd expect to be able to "type at point" on the `WorkQueue`. This breaks ensime / scala-ide support for "jump to definition" etc.

**Comment by raulraja** [comment]
@fommil Thanks for reporting this issue, we have added it to our milestone release and will address it soon. Cheers!

**Comment by raulraja** [comment]
Is this still an issue now that we have migrated all macros to scalameta?

**Comment by fommil** [comment]
scalameta just blows up the PC, so probably ... yes?
