### ISSUE TITLE
please generate Free, not FreeS

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#145]
I was initially very confused about what was being generated https://github.com/47deg/freestyle/issues/143

But now that I understand what is being generated, thanks to http://frees.io/docs/ , I am confused why you're generating `FreeS` instead of `Free`? It may be good if you allow the user to define what they want and generate the necessary boilerplate in either case.

In particular, I don't have any need of `FreeApplicative` at all and this is just adding a layer of complexity onto my interpreters (and biz logic) that I don't need.

**Comment by raulraja** [comment]
@fommil I explained everything in the original issue you opened. `FreeS` is a `Free` and without it you can't do parallelism. There is no need to define anything in the interpreters or biz logic to use it. The same natural transformations and interpreters implementations that work with `Free` should also work with `FreeS`. There is also implicits that lift `FreeS.Par` declarations to `FreeS` when expecting a monad.

**Comment by raulraja** [comment]
Related to #53 #93 as mentioned in https://github.com/47deg/freestyle/issues/143#issuecomment-289448163
