### ISSUE TITLE
Review extension syntax works for lifting to FreeS

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#147]
`state.pure` https://github.com/fommil/drone-dynamic-agents/blob/4572c4eb9fd3f04bebe807effed79a03e8ff16c8/src/main/scala/logic.scala#L61 should have worked

**Comment by peterneyens** [comment]
I don't think this has anything to do with freestyle, this also doesn't work : 

```scala
import cats.syntax.applicative._

import cats.instances.option._
import cats.instances.list._

val a: Option[Int] = 1.pure
val b: List[Int] = 1.pure
```

**Comment by raulraja** [comment]
thanks @peterneyens, my bad, I was under the impression that it would infer the type args from the lhs.
