### ISSUE TITLE
Docs: Play Framework integration

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#162]

**Comment by peterneyens** [comment]
Related to the play integration: The `Action` object is apparently deprecated in Play 2.6. It can still be used in a `Controller` because that now has a `def Action`, but in our case we need to look for a different solution. The deprecation message mentions something about an `ActionBuilder`.

**Comment by raulraja** [comment]
Thanks Peter, I'll get that fixed in the same PR for  the docs
