### ISSUE TITLE
FQN names should use _root_.

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#165]
this file does not compile https://github.com/fommil/drone-dynamic-agents/blob/0d9cf19fd1fd7804e1fc03477251bcf8afbd5c55/src/main/scala/interpreters/oauth2.scala

mostly because when in the package `interpreters.oauth2.client` and referring to `interpreters.oauth2` one may expect the compiler to search from the root, but it starts looking in `interpreters.oauth2.client.interpreters` and fails to find anything.

Admittedly, my packaging convention here is rubbish and the immediate fix is for me to reorganise in a sensible way. But this does point to a more general bug in the macro.

**Comment by diesalbla** [comment]
The following code hits the same problem of unqualified names in macro and ambiguity in package resolution.
```scala
package issue165
import freestyle._
object issue165
@free trait India { def kolkata: FS[Int] }
@module trait Asia[F[_]] {  val india: India[F] }
```

**Comment by raulraja** [comment]
@fommil This PR https://github.com/47deg/freestyle/pull/239 solves the issue but it introduces other problems that may be more important to most users. Among other things FQN in the macro for those types prevents from using expressions in `@module` annotations in the REPL, tut and other tools that use REPL sessions for compiling snippets of code. We are gonna keep this issue open and the branch around in case we can come up with a better solution that does not have this side effects. Here is a sample REPL session snippet. Any ideas to overcome this issue are welcome. Thanks!

```
[info] Set current project to freestyle (in build file:/home/raulraja/Documents/workspace/diegotest/freestyle/)
> console
[info] Starting scala interpreter...
[info] 
Welcome to Scala 2.12.1 (OpenJDK 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.
scala> import freestyle._
import freestyle._
scala> import freestyle.implicits._
import freestyle.implicits._
scala> @free trait X { def x: FS[Int] }
defined trait X
defined object X
scala> @free trait Y { def y: FS[Int] }
defined trait Y
defined object Y
scala> @module trait Z[F[_]] { val x : X[F]; val y : Y[F] }
<macro>:1: error: object Y is not a member of package <root>
type CC$2[AA$2] = Coproduct[_root_.Y.Op, _root_.X.Op, AA$2]
                                   ^
<macro>:1: error: <error> takes no type parameters, expected: one
type CC$2[AA$2] = Coproduct[_root_.Y.Op, _root_.X.Op, AA$2]
                                     ^
<macro>:1: error: object X is not a member of package <root>
type CC$2[AA$2] = Coproduct[_root_.Y.Op, _root_.X.Op, AA$2]
                                                ^
<macro>:1: error: <error> takes no type parameters, expected: one
type CC$2[AA$2] = Coproduct[_root_.Y.Op, _root_.X.Op, AA$2]
                                                  ^
```

**Comment by fommil** [comment]
let's call this fixed, for now. Although we should perhaps use

```
  "-Yno-imports",
  "-Yno-predef"
```

in the tests to be more sure.
