### ISSUE TITLE
"error" algebra elements

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#168]
It would be really useful to be able to generate a kind of `error` algebra element automatically, the kind discussed here https://gitter.im/typelevel/cats?at=58e0fe12f22385553dff68f6 and https://github.com/fommil/drone-dynamic-agents/issues/11

**Comment by raulraja** [comment]
@fommil check out the error effect in the effects section on the docs. That use case should be already supported. Also the Validation effect supports error accumulation.

**Comment by fommil** [comment]
I must admit, I don't fully understand the Effects part of the documentation. I will assume you've covered this and close the ticket and perhaps bother you some more when I try to sit down and understand it. Thanks!

**Comment by raulraja** [comment]
Feel free to reopen or post a small program that you wished it compile with errors and I can adapt it to use the error or validation effects.

**Comment by fommil** [comment]
I think I'm struggling to understand how to include the freestyle effects in my apps using the examples there. But I'll try to figure it out next time. I should probably rewrite some of my business logic to use `State`.
