### ISSUE TITLE
Broken links in the documentation

### ISSUE THREAD

**Issue by n4to4** [47deg/freestyle#174]
There are some broken links in the [doc](http://frees.io/), e.g.: "jump into Parallelism" [at the bottom here](http://frees.io/docs/core/interpreters/).
Also, `grep docs/` shows there are more in the docs and READMEs.

**Comment by peterneyens** [comment]
It seems we broke a few links in #169, @diesalbla.

**Comment by peterneyens** [comment]
Thanks for pointing this out @n4to4.
Fixed by #175.
