### ISSUE TITLE
Enable Kazari in freestyle

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#19]
It's time to test the Kazari integration in the freestyle docs as we approach a first release in January.
Can I get some help integrating Kazari and seeing what it looks like or what potential issues may arise when a project such as Freestyle uses macros? thanks!

**Comment by raulraja** [comment]
Currently blocked by https://github.com/47deg/sbt-microsites/issues/118 & https://github.com/scala-exercises/evaluator/issues/47

**Comment by raulraja** [comment]
There is a new URL now that builds and runs code in Scala 2.12 that we can use for testing this integration http://scala-evaluator-212.herokuapp.com/

**Comment by jdesiloniz** [comment]
Blocked until https://github.com/47deg/sbt-microsites/issues/144 is ready
