### ISSUE TITLE
Add Freestyle to Cats related-projects section

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#193]
https://github.com/typelevel/cats#related-projects

**Comment by raulraja** [comment]
PR requesting this https://github.com/typelevel/cats/pull/1647

**Comment by anamariamv** [comment]
@raulraja,  https://github.com/typelevel/cats/pull/1647 was merged. 
Can we close this issue?

**Comment by raulraja** [comment]
Yes, thank you
