### ISSUE TITLE
Review module macro

### ISSUE THREAD

**Issue by dominv** [47deg/freestyle#221]
This issue is related with #185. When the code snippets from the freestyle docs is run without using objects: 

```scala
import freestyle._
import freestyle.implicits._

  @free trait Validation[F[_]] {
    def minSize(s: String, n: Int): FreeS.Par[F, Boolean]
    def hasNumber(s: String): FreeS.Par[F, Boolean]
  }

  @free trait Interaction[F[_]] {
    def tell(msg: String): FreeS[F, Unit]
    def ask(prompt: String): FreeS[F, String]
  }
  
  @module trait Application[F[_]] {
    val validation: Validation[F]
    val interaction: Interaction[F]
  }
```

the following error is returned: 
```
exception during macro expansion: 
scala.ScalaReflectionException: <none> is not a class
	at scala.reflect.api.Symbols$SymbolApi.asClass(Symbols.scala:272)
	at scala.reflect.api.Symbols$SymbolApi.asClass$(Symbols.scala:272)
	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:88)
	at freestyle.openUnion$.materializeImpl(module.scala:92)
```
The line 92 in `module.scala` is:
```scala
    val algebras   = findAlgebras(weakTypeOf[A].typeSymbol.companion.asClass)
```
And its failing when it calls to the companion method:
```
weakTypeOf[A]: Application.type
weakTypeOf[A].typeSymbol: object Application
weakTypeOf[A].typeSymbol.companion: <none>
```

On the other hand, when using objects, like: 

```scala
import freestyle._
import freestyle.implicits._

object algebras {
  @free trait Validation[F[_]] {
    def minSize(s: String, n: Int): FreeS.Par[F, Boolean]
    def hasNumber(s: String): FreeS.Par[F, Boolean]
  }

  @free trait Interaction[F[_]] {
    def tell(msg: String): FreeS[F, Unit]
    def ask(prompt: String): FreeS[F, String]
  }
}

object modules {
  import algebras._
  
  @module trait Application[F[_]] {
    val validation: Validation[F]
    val interaction: Interaction[F]
  }
}

the results are:
```
```
weakTypeOf[A]: Evaluator__3b8302c6c45f12ee4172cc7128601deeeff5e5d0_1123939886.modules.Application.type
weakTypeOf[A].typeSymbol: object Application
weakTypeOf[A].typeSymbol.companion: trait Application
```

**Comment by dominv** [comment]
This code snippet is failing too:
```scala
import freestyle._
import freestyle.implicits._

    @free trait Validation[F[_]] {
      def hasNumber(s: String): FreeS.Par[F, Boolean]
    }

    @module trait Application[F[_]] {
      val validation: Validation[F]
    }
```

**Comment by diesalbla** [comment]
I have been trying these code snippets, and it seems that the same code work fine when used inside the console (from `sbt freestyleJVM/console`), or when written like that in the projects. This makes me think that the error comes from Kazari. 

Regarding the failing code: the `@module` macro annotation performs a search in depth (recursively) of all the `@free` algebras used, directly or transitively, by the `@module`-annotated trait. The line 92 calls this process and it passes, as its starting point, a `ClassSymbol` of the `Application` trait. A `ClassSymbol` is the internal representation in the [Scala compiler](https://github.com/scala/scala/blob/2.12.x/src/reflect/scala/reflect/internal/Symbols.scala#L3175) of a `trait`. The error suggest that, when running the macro, it is not locating the `trait` `Application` itself.

To narrow down the Trying to narrow down, I have found that the following code fails with the macro companion error.  also fails: 
```scala
import freestyle._
import freestyle.implicits._

@free trait Foo[F[_]] {
  def ann: FreeS[F, Unit]
}
@module trait BarF[_]] {
  val foo: Foo[F]
}
```
However, the following code changes leave to the following results: 
* If we add at the top of the code snippet a `package ops` annotation, then it fails but the error is  in this case the failure says `Compilation Error - ERROR -> List(CompilationInfo(illegal start of statement,Some(RangePosition(139,139,139))))`. 
* If we wrap both `Foo` and `Bar` inside a _same_ object, then the error becomes 
`
Compilation Error - ERROR -> List(CompilationInfo(not found: value Evaluator__[...],Some(RangePosition(16,16,16))))
`

¿Are any of the previous errors known to occur when using Kazari?

**Comment by raulraja** [comment]
The `Evaluator__` piece is a in the fly class in the evaluator that gets compiled and executes what you send to the endpoint in it's `apply` block so definetly looks like an issue with the evaluator.

**Comment by diesalbla** [comment]
We have found [a bug in the Scala Compiler](https://github.com/scala/bug/issues/7567) that may be related to our problem with macros.

**Comment by raulraja** [comment]
This should no longer apply since we moved the macros to scalameta
