### ISSUE TITLE
Attempt to Remove `OpSeq` and `OpPar` in favor of a single `FS`

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#234]
@diesalbla and I discussed offline that it may be possible to treat Ops as Par exclusively and provide proper lifting in to monads implicitly where appropriate. This issue tracks the attempt to remove the verbosity while preserving the feature of paralleling any applicative style composition of those new `FS` ops. This does not need to go in on 0.1.0 but if we have a solution before release we will consider it for inclusion.

**Comment by diesalbla** [comment]
@raulraja There is one possible further improvement that we may now consider: we could avoid the `FS[_]` wrapper completely. What we would do is that, in a `@free` annotated class or method, any abstract method declaration `def ann(x: Int): Bob` would be understood as being an atomic operation of type `FS[Bob]`, i.e., `FreeS.Par[F$, Bob]`, where   `F$[_]` is the type parameter inserted by the macro.

**Comment by raulraja** [comment]
I think we need the wrapper so we can express at some point that it is a monad/applicative and users can directly add concrete methods that compose those return types. I think removing that will add confusion when you realize that you can compose monadically two different types such as `Bob` and `Jane`.
