### ISSUE TITLE
Publish for Scala 2.12

### ISSUE THREAD

**Issue by dvic** [47deg/freestyle#245]
Has the project been published for 2.12? I only see 2.11: https://search.maven.org/#search%7Cga%7C1%7Cfreestyle

Awesome project by the way 👍

**Comment by raulraja** [comment]
Thanks @dvic ! We have snapshots at this time and we are about to send the first 0.1.0 release at the end of this week or beginning of the next one. Snapshots are in sonatype https://oss.sonatype.org/content/repositories/snapshots/com/47deg/

**Comment by dvic** [comment]
Cool, thanks!
