### ISSUE TITLE
Rename `exec`?

### ISSUE THREAD

**Issue by peterneyens** [47deg/freestyle#251]
As it depends of the target type whether or not something is actually executed, the name `exec` is a bit confusing.

There is already the precedent of the method `run` used by `Kleisli`, `StateT` and `WriterT` in Cats (and in all(?) the monad transformers in Scalaz) and this also doesn't "run" something, but if we can come up with a better name, we don't have to follow these bad practices.

**Comment by ShaneDelmore** [comment]
Is it interpret?

**Comment by iamanandkris** [comment]
Is it `transform` as it transforms from Coproduct to another Monad ?

**Comment by raulraja** [comment]
I like `interpret` as @ShaneDelmore mentioned and also like a shorter version `program.to[Future]`. `transform` also works but is widely used as a combinator name in cats for potentially other purposes https://github.com/typelevel/cats/blob/c1dcd408a9f5af9387280cee88beb9f475f08a3c/core/src/main/scala/cats/data/Kleisli.scala#L51 so no sure if it could create confusion when you are interpreting to something such as Kleisli and you may end up with `program.transform[Kleisli[M, D, ?]].transform(...)`

**Comment by iamanandkris** [comment]
Agree with you @raulraja, interpret seems to be a good choice as its actually doing the interpretation.
