### ISSUE TITLE
Ambiguous `freeS`

### ISSUE THREAD

**Issue by peterneyens** [47deg/freestyle#252]
We currently have `.freeS` syntax lifting to `FreeS` for both `FreeS.Par[F, A]` and `F[A]`.

As of #237 we have the `FS` type alias (`FooAlgebra.FS[A] = FreeS.Par[SomeGeneratedF, A]`), which means that `freeS` syntax on `FS[A]` is ambiguous.

**Comment by peterneyens** [comment]
I would suggest to remove the `freeS` syntax for `F[A]`. You would need to have an instance of one of the case classes of the ADT (generated by freestyle) to use this `.freeS`, and that is not something which would happen often if you are using freestyle, I think. If that case comes up, it will still be possible to use `FreeS.liftFA` to go from `F[A]` to `FreeS[F, A]`.

**Comment by diesalbla** [comment]
¿Could we rename it to something more descriptive, such as say `toSeq` or `toFS`?

**Comment by peterneyens** [comment]
@diesalbla The `.freeS` on `FreeS.Par` ?
I think I originally introduced it as `.seq`.

**Comment by raulraja** [comment]
`.seq` may get confusing with either sequencing over the monad or turning into a scala collections `Seq`.
`toFS` as @diesalbla mentioned or just `fs` sounds good to me. Any concerns or other ideas?

**Comment by peterneyens** [comment]
I have the feeling that we might be mixing things here. Currently we have two versions of `.freeS`:

1. `FreeS.Par[SomeF, A]` / `FS[A]` => `FreeS[SomeF, A]`
2. `F[A]` => `FreeS[F, A]`

I suggested to remove the second one. Do you propose to rename it instead?

I think that renaming either one to `.fs` or `.toFS` would be confusing as the result is `FreeS` and not `FS`.

The only place the second `.freeS` is probably used in the freestyle code base itself, is [this test](https://github.com/47deg/freestyle/blob/master/freestyle/shared/src/test/scala/freestyle/syntax.scala#L27) which just check that this syntax works.

**Comment by raulraja** [comment]
Ok, yeah let's remove the second one. sorry for the misunderstanding.
