### ISSUE TITLE
Feature flag Coproduct impl

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#262]
Currently Freestyle can support both cats Coproduct and iota CopK. We should default to the most performant impl which is currently iota but let users choose which one they use via feature flag.

**Comment by andyscott** [comment]
It's also possible to generate both at the same time-- this would be useful for libraries containing free algebras.

**Comment by andyscott** [comment]
I've opened an issue in Iota to support converting to cats coproducts.
