### ISSUE TITLE
Core concepts link in microsite goes to home

### ISSUE THREAD

**Issue by MaureenElsberry** [47deg/freestyle#269]
Core concepts link in microsite goes to home instead of core concepts section

**Comment by suhasgaddam** [comment]
This reminded me of something I noticed when I was reading through the documentation. I probably should create another issue...

The order in the navigation menu does not match how the documentation flows(and is currently linked).

In the documentation, the links follow:
```
Algebras
Modules
Handlers
Parellelism
```

The navigation bar has:
```
Algebras
Handlers
Parellelism
Modules
```
