### ISSUE TITLE
Can't include freestyle as a dependency

### ISSUE THREAD

**Issue by Mullefa** [47deg/freestyle#27]
When I add `freestyle` as a dependency 

```
libraryDependencies += "io.freestyle" %% "freestyle" % "0.1.0"
```

I get:

```
[error] (freestyle-example/*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: io.freestyle#freestyle_2.12;0.1.0: not found
```

**Comment by raulraja** [comment]
There is no released version yet. We are preparing the first release which should be out by the end of January. For the time being you'd have to build from sources. There is an old snapshot here https://oss.sonatype.org/content/groups/public/com/fortysevendeg/freestyle_2.11/0.1.0/ but those will be soon removed as we are also changing the org name in sonatype.

**Comment by Mullefa** [comment]
OK - thanks for letting me know.
