### ISSUE TITLE
Provide automatic stacksafe interpretation for @tagless algebras

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#276]
We should be able to wrap this style of interpreters https://github.com/47deg/freestyle/blob/master/freestyle-tagless/shared/src/test/scala/taglessTests.scala#L108 automatically if the user chooses to interpret a program in a stack safe fashion. 

For example `program[Option]` is stack unsafe but if there is a way for us to lift the value unevaluated so we can do `program[Option @@ Stacksafe]` or `program.interpret[Option]` We could wrap the user defined handlers that are stack unsafe by default automatically into the context of Free without the overhead of the Free ADT currently expanded at `MyAlgebra.StackSafe`. 

The goal is that the user won't need to manually create a handler for `MyAlgebra.Handler[FreeS[Option, ?]]` but just provide one `MyAlgebra.Handler[Option]` and we do the lifting for them.

**Comment by peterneyens** [comment]
As of #310, you can write:

 ```scala
program[Free[Option, ?]].runTailRec
// or
program[StackSafe[Option]#λ].runTailRec
```
