### ISSUE TITLE
Gitter link in README broken

### ISSUE THREAD

**Issue by Mullefa** [47deg/freestyle#28]
I get a `404`. This is not the channel you're looking for.

**Comment by raulraja** [comment]
Hi @Mullefa, we are currently working on publishing the doc site before the first release. The current docs can be seen at https://github.com/47deg/freestyle/tree/master/docs/src/main/tut/docs. Soon the README links will also be fixed. Thanks.

**Comment by raulraja** [comment]
Leaving this open to address it as soon as the doc site goes live.

**Comment by Mullefa** [comment]
OK - thanks for the update 👍
