### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by dominv** [47deg/freestyle#280]
Current test coverage is 73.45%. We need to increase the test coverage above 80 %
 - ` async/shared/src/main/scala/async.scala` - 0.00 %
 - ` freestyle-cache/shared/src/main/scala/cache.scala` - 84.61 % 
 - ` freestyle-cache/shared/src/main/scala/hashmap/HashMapWrapper.scala` - 89.28 % 
 - ` freestyle-cache/shared/src/main/scala/hashmap/Hasher.scala` - 71.42 % 
 - ` freestyle-config/src/main/scala/config.scala` - 0.00 %
 - ` freestyle-config/src/test/scala/config.scala` - 93.33 %
 - ` freestyle-doobie/src/main/scala/doobie.scala ` - 0.00 %
 - ` freestyle-slick/src/main/scala/slick ` - 0.00 %
 - ` freestyle-fs2/shared/src/main/scala/fs2.scala` - 95.00 %
 - ` freestyle-slick/src/test/scala/slick ` - 0.00 %
 - ` freestyle/shared/src/main/scala/freestyle/Capture.scala` - 33.33 %
 - ` freestyle/shared/src/main/scala/freestyle/Implicits.scala` - 50.00 %
 - ` freestyle/shared/src/main/scala/freestyle/InjK.scala` - 0.00 %
 - ` freestyle/shared/src/main/scala/freestyle/NonDeterminism.scala` - 28.57 %
 - ` freestyle/shared/src/main/scala/freestyle/package.scala` - 68.75 %
 - ` freestyle/shared/src/test/scala/freestyle/InjK.scala` - 72.72 %
 - ` http/http4s/src/main/scala/http/http4s.scala` - 50.00 %
 - `http/play/src/main/scala/play.scala` - 0.00 %

**Comment by peterneyens** [comment]
There are a couple of places where I don't understand the 0%, for example the `freestyle-slick` and `freestyle-doobie` modules.

**Comment by dominv** [comment]
@peterneyens Initially, I'm going to check that `codecov` is well configured and then I'll check what's happening with the tests. In some cases there already are tests but they seem not to be correctly configured. I'll take care of it.

**Comment by juanpedromoreno** [comment]
I potentially have a guess about the code coverage.

Follow my attempt here: https://github.com/47deg/freestyle/pull/285

BTW, any concern replacing `AsyncWordSpec` by just `WordSpec`?

* _Update_: no clue where the problem is. Codecov still interprets test classes as standard source code :(

**Comment by dominv** [comment]
This issue has been divided in the above issues.
