### ISSUE TITLE
FQN needed to Any

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#312]
this is going to sound really weird, but I am experimenting with flag `-Yno-imports` (stop laughing at the back!) and my (drone-dynamic-agents) tests fail with

```
[error] Handler not found to transform `logic.Deps.Op` to `cats.Id`
```

unless I `import scala.Any`. It would be good if everything was FQN in the macro code.

**Comment by raulraja** [comment]
Makes sense, we'll take a look, thanks @fommil for reporting this. We are also interested in supporting alternative predefs.

**Comment by fommil** [comment]
sorry for being this guy

![this guy](https://imgs.xkcd.com/comics/purity.png)

**Comment by fommil** [comment]
and `AnyRef` by the looks of it
