### ISSUE TITLE
suppress wartremover:Any

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#313]
This may not be possible to change... but I've been experimenting with wartremover

```
wartremoverWarnings in (Compile, compile) := Warts.unsafe
```

and `@free` is giving me this wart

```
[warn] /home/fommil/Projects/drone-dynamic-agents/src/main/scala/algebra.scala:15: [wartremover:Any] Inferred type containing Any
[warn]   @free trait Drone {
```

If it's not possible to avoid this, perhaps the `@java.lang.SuppressWarnings(scala.Array("org.wartremover.warts.Any"))` (note FQNs) annotation should be added to skip this wart? http://www.wartremover.org/doc/install-setup.html

**Comment by raulraja** [comment]
@fommil Thanks for reporting this!. I expect more of this to show up as we keep introducing optimizations.

**Comment by fommil** [comment]
maybe adding wartremover to your own build would catch it at dev time? Upfront cost can be a pain though.

**Comment by fommil** [comment]
close for #314
