### ISSUE TITLE
can't be used with wartremover

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#314]
sorry, me again, wartremover points out that `@free` generated `case class`es should be final and that implicits in `@module` should have an explicit description (I assume that means type parameter?)

I guess suppressing them is possible, but these ones seem like they could be easily fixed.

**Comment by raulraja** [comment]
Keep them coming, it'd be easier to address all the wart-remover warnings in a single PR since most of them will come from the macros.

**Comment by diesalbla** [comment]
@fommil We have recently released `0.2.0` and updated the macros. To follow up with this issue, ¿could you tell us how we can reproduce the issues you were having?

**Comment by fommil** [comment]
Just add wartremover in your tests. `wartremoverErrors in Test = ...`

**Comment by fommil** [comment]
seeing lots of `StringPlusAny` warnings in 0.2.0, and also `StringContext` need to be in scope to use `@free`

**Comment by fommil** [comment]
and `Throw`.

OK, starting to look like all the warts are brokened :stuck_out_tongue_closed_eyes:

**Comment by fommil** [comment]
hmm, I'm trying by adding this to `tests`

```scala
    wartremoverWarnings := Warts.unsafe ++ Seq(
      Wart.FinalCaseClass,
      Wart.ExplicitImplicitTypes
    ),
```

and this to `project/plugins.sbt`

```
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.0.3")
```

but it's not kicking in... hmm
