### ISSUE TITLE
Remove Coproduct materializer macro in favor of Iota's Coproduct Concat support

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#325]
This is necessary to decrease compilation times caused by the second macro expansion that we had to add due to missing information in scala reflect Trees when calculating nested recursive Coproducts.

**Comment by diesalbla** [comment]
I think that this PR https://github.com/frees-io/freestyle/pull/326 has already solved this issue. The builds seem to have stabilised. ¿Is there anything else needed?

**Comment by andyscott** [comment]
I think this issue is closed. If we want to support `cats.data.Coproduct`, I can add a conversion utility into Iota so that there's no work to do in Freestyle.
