### ISSUE TITLE
Rework docs site style

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#332]
This issue track reworking the docs design to make them more readable and slick now that we have a better understanding about the sections.

**Comment by raulraja** [comment]
Here are the sections that should go on the index:
- Freestyle (Main Logo and tagline)
- 6 Main items: Algebras(simple heragon logo), Modules (Combination of hexagon), Handlers (Gears runtime), Effects, Integrations, RPC Microservices, Cassandra, Kafka

**Comment by nmeln** [comment]
@raulraja Would it make sense to also add Search field to allow faster navigation?

**Comment by raulraja** [comment]
@ranchoiver yes but this should be implemented in sbt-microsites which is the doc generator tool we are using https://github.com/47deg/sbt-microsites . Added https://github.com/47deg/sbt-microsites/issues/196 to track it.

**Comment by israelperezglez** [comment]
- [x] UI Design home
---
- [x] Effects icon
- [x] Cassandra icon
- [x] RPC icon
- [x] Kafka icon
---
- [x] UI Design doc
---
- [ ] Hmlt-css home
- [ ] Hmlt-css doc

**Comment by israelperezglez** [comment]
Fixed https://github.com/frees-io/freestyle-design/pull/1
