### ISSUE TITLE
Travis Build: Coverage and JS

### ISSUE THREAD

**Issue by diesalbla** [47deg/freestyle#347]
We have found before that Codecov has some compatibility problems with ScalaJS. As a result, when building the `orgScriptCI` using the ScalaJS backend, we usually find some problems. The goal of this ticket is to avoid this from the build script. 

One possible solution to do this is the following one: 
* Separate `.travis` builds for the JS and the JVM, by using an [environment variable](https://docs.travis-ci.com/user/build-stages/matrix-expansion/) that would split two sub-builds, as we do with versions of Scala.
* In `sbt`, create specialized tasks for `JVM` or `JS`, that only run the usual tasks for the JVM projects or the JS projects. The one for `JS` should not include `codecov`.

**Comment by raulraja** [comment]
Is there a way to just tell codecov to not consider the JS modules as sources?

**Comment by juanpedromoreno** [comment]
Not explicitly, I have a way to do it though. I'll cut off my branch from this one: `DA-73-ScalaMeta_Migration`
