### ISSUE TITLE
Integrate case classy in config algebras

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#36]
Case class supports now derivation of codecs for product types so config can be mapped directly to things like classes. On top of that it supports also access to the most common combinators provided by libs like Typesafe Config and a module for shocon wich would allow us to remain compatible with ScalaJS //cc @andyscott

**Comment by andyscott** [comment]
Would you like me to take a stab at this?

**Comment by raulraja** [comment]
@andyscott Yes please! The original intent is to replace this https://github.com/47deg/freestyle/blob/master/freestyle-config/shared/src/main/scala/config.scala with a case classy based implementation that supports an operation for also parsing configs to case classes and still supports the existing algebra operations. Thanks!

**Comment by andyscott** [comment]
I won't be able to get this done by today-- I will work on it over the next few days, though, as I prep some more work for Case Classy!

**Comment by raulraja** [comment]
@andyscott What's the status of this issue? thanks!

**Comment by anamariamv** [comment]
Merged #378
