### ISSUE TITLE
Missing dependency 'object scala in compiler mirror' when running `sbt console`

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#364]
[init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar(java/lang/Object.class) [error] (run-main-0) java.lang.reflect.InvocationTargetException

**Comment by LGLO** [comment]
I'm afraid that it problem outside _freestyle_.

I have made a project with simple build.sbt:
```
scalaVersion := "2.12.2"
addCompilerPlugin("org.scalameta" %% "paradise" % "3.0.0-M9" cross CrossVersion.full)
```
With no dependency on _freestyle_ and it exhibit same error.

**Comment by raulraja** [comment]
More info on the subject, seems like the macroparadise plugin for scalameta does not work in the REPL yet:
http://scalameta.org/tutorial/#Setupbuild
https://github.com/scalameta/paradise/issues/10

**Comment by raulraja** [comment]
Looks like adding:
```
scalacOptions += "-Xplugin-require:macroparadise",
scalacOptions in (Compile, console) := Seq() 
```
to the scala meta option in sbt will make it not crash but not sure it's gonna expand the macros either.
