### ISSUE TITLE
Cache Algebras

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#37]
We should provide a simple algebra with the most common operations for caching. This may be able to reutilize `StateM` generic in the target type of the cache storage so we can build storages for common integrations such as Redis and other related libs in the caching space.

**Comment by diesalbla** [comment]
These are a few extra notes on the ticket: 

We should define an algebra for basic operations of a cache, or any Key-Value store, such as `get`, `put`, `delete`, or others. Then we should create two implementations for this algebra:
* One implementation is backed by a concurrent in-memory map, such as [Java `ConcurrentHashMap`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html). This implementation would work both in the JVM and JavaScript.
* Another implementation is based on a [`Redis`](https://redis.io/) client, with the data being stored in a `Redis` server. The parameters for the connection are to be fetched through the `freestyle-config` module.
