### ISSUE TITLE
types returning source locations in macro code

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#372]
in https://github.com/ensime/ensime-server/issues/1813 I found out that the source location for my algebra, `Drone`, as reported by the presentation compiler, is coming back as `OffsetSourcePosition(RawFile(<macro>),298)),List())`

That doesn't sound right... I am not sure if this is an ensime, presentation compiler, scala.meta or freestyle bug. // @xeno-by

**Comment by fommil** [comment]
(btw, I'm not sure if `<macro>` has come from our indexer ... which will mean the raw `.class` file's debug information... or the PC at this point)

**Comment by xeno-by** [comment]
`<macro>` probably comes from a position that was assigned to a scalameta/paradise macro expansion. Are you using such a macro?

**Comment by fommil** [comment]
yes, the type of the thing at point is generated by a macro.

**Comment by fommil** [comment]
I would really prefer it if the position information was for the containing file, and the line number was the line of the original, as a "transparent position".

**Comment by xeno-by** [comment]
@fommil Would you consider contributing a patch that does this? Here's the relevant piece of logic in scalameta/paradise: https://github.com/scalameta/paradise/blob/master/plugin/src/main/scala/org/scalameta/paradise/typechecker/Expanders.scala#L183-L186. /cc @olafurpg

**Comment by fommil** [comment]
thanks! If I find the time, I will try to have a go. How can I access the original file's name and source line from here?

**Comment by xeno-by** [comment]
I think `original.pos` should be a way to go.
