### ISSUE TITLE
Be consistent with the `Op` wording

### ISSUE THREAD

**Issue by pepegar** [47deg/freestyle#382]
When developing https://github.com/frees-io/freestyle/pull/353, i needed to pattern match on the cases of the ADT generated by a `@free` algebra. In those cases, the `OP` suffix is added to the name of the method, capitalized.

Also, on `@module` annotated traits, a  `Op` type is used to refer to the operation.

As of my understanding both refer to `operation`, so it would be great to use the same term for both, either `OP` or `Op`. It's not a biggie, but I needed to investigate a bit further asking scalac to expand the macro for me to figure out that in ADT cases, it's `OP`.

**Comment by raulraja** [comment]
Makes sense, we should take care of this before 0.4.0. Thanks for reporting it :)
