### ISSUE TITLE
Consider renaming modules to `frees-*`

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#383]
In a conversation on gitter in typelevel/general with @edmundnoble and other folks this came up... Should we rename modules from `freestyle-*` to `frees-*`, `somethingelse-*`?
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BN1DXCHDM8YPVSSPSNXQVAG1/Rename%20libs%20to%20%60frees-*%60)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BN1DXCHDM8YPVSSPSNXQVAG1/Rename%20libs%20to%20%60frees-*%60/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BN1DXCHDM8YPVSSPSNXQVAG1/Keep%20current%20%60freestyle-*%60)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BN1DXCHDM8YPVSSPSNXQVAG1/Keep%20current%20%60freestyle-*%60/vote)

Please, feel free to comment if you have an opinion about this:

**Comment by andyscott** [comment]
Would the core module remain `freestyle` or would we rename that to just `frees`?

**Comment by edmundnoble** [comment]
I was aiming for the core remaining `freestyle`, myself.

**Comment by pepegar** [comment]
Maybe it's worth to set up a poll?

http://gh-polls.netlify.com/

**Comment by raulraja** [comment]
Thanks @pepegar I updated the description

**Comment by raulraja** [comment]
@andyscott @edmundnoble I think `frees` would be consistent with other libs naming like `cats` where the core is just the prefix but I think keeping it `freestyle` would also work.

**Comment by raulraja** [comment]
Let's keep this open until Monday/Tuesday to give folks a chance to vote and voice their opinions.

**Comment by fommil** [comment]
obvz the scalaz port will be `freez`

**Comment by andyscott** [comment]
If we rename to frees, I would vote for renaming the core module to frees-core for the sake of consistency. It's consistent naming for our modules, and also consistent naming with other libs across the Scala community.
