### ISSUE TITLE
Rename `freestyle-*` modules to `frees-*`

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#386]
Action derived from https://github.com/frees-io/freestyle/issues/383 to be applied before 0.4.0

**Comment by peterneyens** [comment]
freestyle, freestyle-integrations and freestyle-docs have been changed. 
Do we leave this issue open until freestyle-kafka, freestyle-cassandra, freestyle-rpc, ... have change as well?

**Comment by juanpedromoreno** [comment]
`freestyle-rpc` has been already renamed 👍
