### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by bhericher** [47deg/freestyle#390]
Actually, the version of macroparadise is 3.0.-M9 :

addCompilerPlugin("org.scalameta" %% "paradise" % "3.0.0-M9" cross CrossVersion.full)

it should be 3.0.0-M**10**

**Comment by anatoliykmetyuk** [comment]
Depends on the Scala version you are using. Certain milestones are supported under certain Scala versions. I think it is worth mentioning that you should consult [Maven Search](http://search.maven.org/#search%7Cga%7C1%7Cscalameta.paradise) and set the version according to your Scala version.

**Comment by bhericher** [comment]
You're right, thank you
