### ISSUE TITLE
Refactor: Migration to cats 1.0.0, cats-effects and mtl effects constrains

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#391]
We need to get to this before 0.4.0

**Comment by guersam** [comment]
Is there something I can help with?

**Comment by raulraja** [comment]
@peterneyens do you need any help with this from @guersam ?

**Comment by peterneyens** [comment]
The migration is mostly done. Thanks for offering @guersam.

I might have found an issue with iota which would need to be fixed before I can put up a PR that passes all the tests.

**Comment by guersam** [comment]
Thanks for checking out. Looking forward to it!

**Comment by peterneyens** [comment]
For the moment the modules in this repo need a release from `cats-mtl` for 2.11 and a release for iota.

For the freestyle-integrations there are a lot of dependencies which have only milestones, for http4s there are only snapshots and for finch I don't think there is anything yet.

We will probably publish a milestone for the modules in these repo once we have cats-mtl and iota and update freestyle-integrations and freestyle-docs later on.

**Comment by guersam** [comment]
FYI: `cats-mtl` 0.0.2 for Scala 2.11 has been published on maven central as of 26 Aug.

**Comment by alari** [comment]
Hi! Are there any schedule when you're going to release a version of freestyle for cats 1.0?
Thanks!
