### ISSUE TITLE
Support implicit args in @tagless abstract methods

### ISSUE THREAD

**Issue by rafaparadela** [47deg/freestyle#403]

**Comment by enricsangra** [comment]
Is it possible to have a test to understand the specifics of the problem?

**Comment by raulraja** [comment]
@rafaparadela can you provide @enricsangra with a reduced case that reproduces the error?

**Comment by juanpedromoreno** [comment]
This would be the ignored test reproducing this issue:

https://github.com/frees-io/freestyle/blob/1044127cc46d9192ea1949277609adbf8be7acda/modules/core/shared/src/test/scala/freestyle/tagless/TaglessTests.scala#L80

**Comment by juanpedromoreno** [comment]
It might be handy to have another test for this case:

```scala
trait Generic[A]

"a trait with some implicit generic parameter, with standard params" ignore {
  "@tagless trait X { def f[T](a: Int)(implicit b: Generic[T]): FS[Int] }" should compile
}
```

**Comment by diesalbla** [comment]
This issue has been implemented recently. There is a test [here](https://github.com/frees-io/freestyle/blob/6cf4bdec2cff1f029779e1ec45e986dbd701c546/modules/core/shared/src/test/scala/freestyle/tagless/TaglessTests.scala#L225).
