### ISSUE TITLE
Update dependency org.scalameta:scalameta

### ISSUE THREAD

**Issue by 47degfreestyle** [47deg/freestyle#406]
Actual version: 1.8.0
 Patch: -
 Minor: -
 Major: 2.0.1

**Comment by andyscott** [comment]
Heads up: 2.0.1 currently doesn't support annotation macros, so I don't believe this update can be done.

**Comment by AdrianRaFo** [comment]
sbt-org-policies 0.8.20 upgrade scalameta to 2.1.5
