### ISSUE TITLE
frees.io docs sidebar bad loading

### ISSUE THREAD

**Issue by calvellido** [47deg/freestyle#450]
With new Freestyle webpage and Freestyle Docs deployment, we have had some users reporting that when navigating through [frees.io/docs](http://frees.io/docs), the sidebar gets totally translated to left from the right on menu item clicking.

This could be a symptom of the CSS styling not getting properly cached on the browser for some reason. Weird thing is that only happens to some users, but not to others.

This ticket includes the requirement to do some research on the conditions needed to be met to trigger this behaviour, and a a global solution for all users/browser/OS.

**Comment by calvellido** [comment]
Related -> 47deg/sbt-microsites#75

**Comment by calvellido** [comment]
This will be fixed by using `sbt-microsites` version ^0.7.11 when it sails, which includes changes addressing this problem.

More info can be checked on this PR: 47deg/sbt-microsites#243

**Comment by raulraja** [comment]
@juanpedromoreno can we make a release with this?

**Comment by fedefernandez** [comment]
* [x] Release sbt-microsites 0.7.11 version - [47deg/sbt-microsites/pull/244](https://github.com/47deg/sbt-microsites/pull/244)
* [x] Release sbt-org-policies 0.8.18 using the  sbt-microsite 0.7.11 version
* [x] Release sbt-freestyle 0.3.13 using the sbt-org-policies 0.8.18 version
* [x] Bump sbt-freestyle version in freestyle and publishMicrosite
 or
* [x] Release a new freestyle version using the sbt-freestyle 0.3.13 version

**Comment by juanpedromoreno** [comment]
Yep, we are following now the steps indicated by @fedefernandez .

**Comment by juanpedromoreno** [comment]
Finished, it should be ready shortly.

CC @calvellido @raulraja
