### ISSUE TITLE
Proposal: Simplify Tagless

### ISSUE THREAD

**Issue by diesalbla** [47deg/freestyle#478]
The `@tagless` macro at present is generating some elements which, in the context of the [tagless-final](http://okmij.org/ftp/tagless-final/) encoding, are redundant.

#### Trait Handler

At present, for the following program: 

```Scala
@tagless trait Foo { 
  def foo(x: Int): FS[Boolean]
}
```

The `@tagless` macro annotation generates the following in the companion object: 
```Scala
trait Foo[F[_]] extends TaglessEffectLike[F] { 
  def foo(x: Int): FS[Boolean]
}

object Foo {
  trait Handler[M[_]] extends Foo[M] {
    def foo(x: Int): M[Boolean]   
  }
  [....]
}
```
I am not sure if this `trait`  definition adds anything, since the `Handler` and the `Foo` contain exactly the same thing. Thus, I would suggest to replace that trait with a type alias
```Scala
object Foo {
   type Handler[M[_]] = Foo[M]
}
```

#### Stack safe Free Handler
One feature of `@taglesss` is to use `@free` annotation to generate a stack-safe interpretation, into the `Free` monad itself. Now `@free` generates a companion object for the Stacksafe algebra, and this later companion also contains a `Handler` definition. And, finally, `@tagless` itself provides a default implementation of this handler. 

To make this clear, expanding both `@tagless` and the inner `@free` would leave this code (abridged): 
```Scala
trait Foo[F[_]] extends TaglessEffectLike[F] { 
  def foo(x: Int): FS[Boolean]
}

object Foo {
  trait Handler[M[_]] extends Foo[M] {
    def foo(x: Int): M[Boolean]   
  }

  trait StackSafe[F[_]] extends FreeEffectLike[F] {
    def foo(x: Int): FS[Boolean]
  }
  object StackSafe {
    [....]
    trait Handler[M[_]] extends (Op ~> M) {
      def foo(x: Int): M[Boolean]     
    }
  }

  implicit def stackSafeHandler[M[_]](implicit ev: Monad[M], hh: Handler[M]): StackSafe.Handler[M] = 
    new StackSafe.Handler[M] {
      def foo(x: Int): M[Boolean]  = hh.foo(x)
    }
  [....]
}
```
I think that the same effect can be achieved, with a bit less hastle, but just making the extended trait 
The same effect would be achieved if we could add an inheritance to the initial `Foo` trait, like follows: 

```Scala
trait Foo[F[_]] extends TaglessEffectLike[F] with Foo.StackSafe.Handler[F] { 
  def foo(x: Int): FS[Boolean]
}
```
Together with the previous alias, we could now remove the `stackSafeHandler` method itself (the implicit `Handler` would become `implicit Foo`, which itself would be `StackSafe.Handler`·

**Comment by raulraja** [comment]
👍
