### ISSUE TITLE
Javadoc jars on repo1.maven.org are in actual fact copies of the freestyle README

### ISSUE THREAD

**Issue by jedahu** [47deg/freestyle#482]
```bash
curl -s https://repo1.maven.org/maven2/io/frees/frees-core_2.12/0.5.0/frees-core_2.12-0.5.0-javadoc.jar | file -
# => /dev/stdin: HTML document, ASCII text, with very long lines
```

The HTTP response is a copy of the freestyle README.md.

It is the same with other frees-io projects like iota.

**Comment by AdrianRaFo** [comment]
Is caused by https://github.com/frees-io/sbt-freestyle willfully because scaladoc doesn't work with macros

**Comment by jedahu** [comment]
That explains it. Thanks.
