### ISSUE TITLE
Update to Cats 1.0.0

### ISSUE THREAD

**Issue by anamariamv** [47deg/freestyle#487]

**Comment by mwz** [comment]
Is this blocked by https://github.com/47deg/sbt-org-policies/issues/655 or can cats be upgraded independently from `sbt-org-policies`?

**Comment by juanpedromoreno** [comment]
Nop, it isn't. It can be updated independently.

**Comment by AdrianRaFo** [comment]
Blocked by https://github.com/frees-io/iota/issues/105
```
exception during macro expansion: 
[error] java.lang.NoSuchMethodError: cats.FlatMap$Ops.$greater$greater$eq(Lscala/Function1;)Ljava/lang/Object;
[error]         at iota.internal.catryoshka$.$anonfun$hyloM$1(catryoshka.scala:58)
```

**Comment by juanpedromoreno** [comment]
It shouldn't be blocked. We need this PR merged https://github.com/frees-io/iota/pull/106 and afterward a new release.

**Comment by AdrianRaFo** [comment]
I make a publish local of the Iota's new release but still blocked by doobie which is blocked by fs2
https://github.com/tpolecat/doobie/pull/650
