### ISSUE TITLE
Cannot find tagless 0.5 on maven central

### ISSUE THREAD

**Issue by romainreuillon** [47deg/freestyle#498]
Dear devs,

tagless 0.5.1 is not resolving in my sbt build:
```
[warn] 	module not found: io.frees#frees-tagless_2.12;0.5.1
[warn] ==== local: tried
[warn]   /home/reuillon/.ivy2/local/io.frees/frees-tagless_2.12/0.5.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/frees/frees-tagless_2.12/0.5.1/frees-tagless_2.12-0.5.1.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/reuillon/.sbt/preloaded/io.frees/frees-tagless_2.12/0.5.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/reuillon/.sbt/preloaded/io/frees/frees-tagless_2.12/0.5.1/frees-tagless_2.12-0.5.1.pom
```

Despite I am able to find the 0.5.1 of freestyle in the central maven repos:
https://mvnrepository.com/artifact/io.frees/frees-core

I am not able to find tagless:
https://mvnrepository.com/artifact/io.frees/frees-tagless

Any idea why it might be so?

Cheers,
Romain

**Comment by AdrianRaFo** [comment]
Hi @romainreuillon, since 0.5.0 version frees-tagless is part of frees-core.
If you try `import freestyle.tagless._`, it should found it and `import freestyle._` has to be changed to `import freestyle.free._`.
I hope I've helped :slightly_smiling_face:

**Comment by romainreuillon** [comment]
Great, thanks!
