### ISSUE TITLE
@tagless issue with StackSafe expansion

### ISSUE THREAD

**Issue by juanpedromoreno** [47deg/freestyle#517]
The following code doesn't compile:

```scala
object test {
  @tagless trait TestF[F[_]] {
    def foo(f: Int => F[String]): F[String]
  }
}
```

It produces:

```bash
[error] <macro>:13:42: not found: type F
[error]       final case class AOp(val f: Int => F[String]) extends _root_.scala.AnyRef with Op[String] { override val FSAlgebraIndex6: _root_.scala.Int = 0 }
[error]                                          ^
[error] <macro>:13:42: not found: type F
[error]       final case class AOp(val f: Int => F[String]) extends _root_.scala.AnyRef with Op[String] { override val FSAlgebraIndex6: _root_.scala.Int = 0 }
[error]                                          ^
[error] <macro>:16:41: not found: type F
[error]         protected[this] def a(f: Int => F[String]): MM$12[String]
[error]                                         ^
[error] <macro>:27:34: not found: type F
[error]         override def a(f: Int => F[String]): FS[String] = toInj10(AOp(f))
[error]                                  ^
[error] <macro>:13:42: not found: type F
[error]       final case class AOp(val f: Int => F[String]) extends _root_.scala.AnyRef with Op[String] { override val FSAlgebraIndex6: _root_.scala.Int = 0 }
```

**Comment by diesalbla** [comment]
@juanpedromoreno Regarding the examples you put above, I am afraid that the use of the algebra's carrier type parameter be it `FS[_]` or `F[_]`, has problems not only with the `Stacksafe` class and trait, but also with the `mapK` function as well. 

The `mapK` function allows you to translate a `TestF[F]` into a `TestF[M]`, by applying the natural transformation from F to M to each request method: 
```Scala
@tagless trait TestF[F[_]] { self => 
  def ann: F[String]

  def mapK[M[_]]( nt: F ~> M): TestF[M] = new TestF[M]{
    def ann: M[String] = nt(self.ann)
  }
}
```

But in the case of your function `def foo(f: Int => F[String]): F[String]`, in the result of `mapK` it would need to have the signature  `def foo(f: Int => M[String]): M[String]`, so you need to transform not just the result, but also the input parameter `f`; and this one needs to take a natural transformation in the other sign, `M ~> F`. 

The same would happen with any input parameter that used the `FS` or `F` carrier in the parameter type, such as: 
```Scala
@tagless trait TestF {  
  def ann(s: FS[String]): FS[String]
}
```
Or if we wanted to use the type `FS` inside the return type: 

```Scala
@tagless trait TestF {  
  def ann(s: String): FS[OptionT[FS, String]]
}
```
In this case, we would need to pump the transformation through OptionT. I don't think there is a general solution for simultaneously moving the type `FS` **_both_** in the outermost appearance of the return type, and inside a parameter's or inside the return type.

**Comment by diesalbla** [comment]
I am going to open another issue to update the documentation with the changes in `@tagless`.
