### ISSUE TITLE
Tagless macro contains insecure code

### ISSUE THREAD

**Issue by AdrianRaFo** [47deg/freestyle#560]
we cannot do `Option.get` https://github.com/frees-io/freestyle/blob/master/modules/core/shared/src/main/scala/freestyle/tagless/internal/tagless.scala#L54
We need to proceed on a safe way and return a properly error

**Comment by diesalbla** [comment]
There is now a [`cats-tagless`](https://github.com/typelevel/cats-tagless), which is actively maintained, already ported out of `scalameta`, and has wider functionalities than freestyle `@tagless` macros.
