### ISSUE TITLE
ensime/scala-ide support: i.e. tests with pcplod

### ISSUE THREAD

**Issue by fommil** [47deg/freestyle#67]
You don't need to do anything special for it to "just work" in ensime and scala-ide, but you might find that you have bugs that break position information when the compiler enables them. I can try to help you fix it if the tests don't pass.

To ensure that you cover this use-case, please make sure to add a pcplod unit test https://github.com/ensime/pcplod

btw, I'm really looking forward to when this is ready for release, so I can use it in
https://github.com/fommil/drone-dynamic-agents/blob/master/src/main/scala/algebra.scala !

**Comment by raulraja** [comment]
@fommil Thanks! When you say bugs, do you mean in the way the Macro generates the code?. I'll look into pcplod too.

**Comment by fommil** [comment]
yup, both bugs in the macro and - potentially - bugs in macro paradise or the compiler macro impl. If we find anything of the such, Eugene Burmako is very keen to look into it.

**Comment by raulraja** [comment]
@fommil I've gotten this far but unsure as to what to do with it: https://github.com/47deg/freestyle/pull/68
