### ISSUE TITLE
Migrate macros to Scala meta to enable IDEA support

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#73]
When we started freestyle scala meta and it's macro paradise support had issues with HKTs. Now that scala meta is becoming more stable we should consider dropping the macro code in favor of a version with Scala meta if possible.

https://github.com/scalameta/paradise/issues/59

**Comment by raulraja** [comment]
This has been promoted to very important as it seems IDEA supports scala meta in some capacity and when we move it over it may take care of #58 which is currently blocked.

**Comment by juanpedromoreno** [comment]
Fixed in #344
