### ISSUE TITLE
ValidationM Effect Algebra

### ISSUE THREAD

**Issue by raulraja** [47deg/freestyle#83]
In the same way the `ErrorM` effect implements a fail fast strategy that immediately stops computation upon an error and relies on the presence of a `MonadError` instance for `M[_]` in the interpreter it should possible to have an algebra for Validation which places similar constrains.

In contrast to `ErrorM`, `ValidationM` should be able to accumulate errors and rely in something like `MonadState` in the final interpreter to accumulate errors over the computation and make them available at any point in the program.

The `ValidationM` algebra may tentatively look something like this:

```scala
trait ValidationProvider[E, A] {
  @free trait ValidationM[F[_]] {
       def valid(a: A): FreeS.Par[F, A] //lifts a valid value in the validation context
       def invalid(a: A): FreeS.Par[F, Unit] //accumulates an error in the validation context
       def validation: FreeS.Par[F, ValidatedNel[E, A]] // return the current state of the validation context
       def errors: FreeS.Par[F, List[E]] // returns a list of errors from the validation context
  }
}
```

**Comment by raulraja** [comment]
Other useful combinators in this algebra may be automatically lifting into the validation state the following values:
* from Option[A] 
* from Either[E, A] 
* from ValidatedNel[E, A]

**Comment by peterneyens** [comment]
I am not sure you could combine this `ValidationM` effect with the `StateM` effect if it is also based on `MonadState`, because I don't think you can have multiple `MonadState` constraints for different kind of states.

---

Example :

```scala
import cats.implicits._
import cats.MonadState
import cats.data.{State, StateT}

type ValidationIntState[A] = StateT[State[Int, ?], List[String], A]

MonadState[ValidationIntState, List[String]]
// cats.MonadState[ValidationIntState,List[String]] = cats.data.StateTInstances$$anon$3@56c6d53d

MonadState[ValidationIntState, Int]
// error: could not find implicit value for parameter F: cats.MonadState[ValidationIntState,Int]
//        MonadState[ValidationIntState, Int]
```
